### PR TITLE
[SEMVER-MAJOR] disallow undeclared variables

### PR DESCRIPTION
**Pull request by yshing**
http://eslint.org/docs/rules/no-undef

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by bajtos** [comment]
👍

**Comment by bajtos** [comment]
@slnode test please

**Comment by kjdelisle** [comment]
@bajtos  I'd make use of this option instead: http://eslint.org/docs/rules/global-strict#options
Originally, this was auto-enforced by eslint@1.x, and was removed in 2.x

**Comment by bajtos** [comment]
> I'd make use of this option instead: http://eslint.org/docs/rules/global-strict#options
> Originally, this was auto-enforced by eslint@1.x, and was removed in 2.x

@kjdelisle I don't understand. We are already requesting global strict mode, see https://github.com/strongloop/eslint-config-loopback/blob/eb90bd45cd1ded8910ace27e274d72b70566ec3c/eslint.json#L47

This pull request is adding a check for undefined variables in the linter, so that we don't have to wait for runtime to discover them. (At least that's my understanding.)

What am I missing?

**Comment by superkhau** [comment]
> This pull request is adding a check for undefined variables in the linter, so that we don't have to >wait for runtime to discover them. (At least that's my understanding.)
> 
> What am I missing?

+1, I am also confused as our rule already checks for global strict mode.

**Comment by superkhau** [comment]
I'm also confused as the global strict mode seems to have nothing to do with this PR? As far as I'm concerned, this PR LGTM.

**Comment by bajtos** [comment]
Landed, thank you for the contribution! Note that this change will be released in a new major version, projects have to opt-in to use this new version (and fix any undeclared variables first).

**Comment by bajtos** [comment]
Released as `eslint-config-loopback@5.0.0`

**Pull request merged**
