### PR TITLE
Tweak the config to follow loopback style

### PR DESCRIPTION
**Pull request by bajtos**
Use the style in loopback-boot, it is supposed to be as close to the agreed-upon coding style as possible.

Connect to strongloop/loopback#1749

@superkhau please review
/cc @strongloop/loopback-dev

### CODE REVIEW

**Comment by bajtos** [comment]
One thing to consider: the latest eslint allows us to use verbose level names (off, warn, error) instead of numbers (0,1,2). Should I change all numbers to strings as part of this change? Update README?

@superkhau thoughts?

**Comment by superkhau** [comment]
> One thing to consider: the latest eslint allows us to use verbose level names (off, warn, error) instead of numbers (0,1,2). Should I change all numbers to strings as part of this change? Update README?

I agree with clarity over brevity. :+1: Please update.

**Comment by superkhau** [comment]
The only negative I can think of is not being able to copy/paste from the eslint website (since they use shorthand level names, but it's not a big deal).

**Comment by superkhau** [comment]
LGTM

**Comment by bajtos** [comment]
> I agree with clarity over brevity. :+1: Please update.

Done in deab660

**Pull request merged**
