### PR TITLE
[SEMVER-MAJOR] Add multi space check

### PR DESCRIPTION
**Pull request by deepakrkris**
Add lint option to not allow multispaces
- http://eslint.org/docs/rules/no-multi-spaces

cc @bajtos

### CODE REVIEW

**Review by superkhau — APPROVED** [review]

**Comment by rmg** [comment]
Take note of the downstream failures identified by CI - those are packages that will start failing on CI when this PR gets merged if they are not fixed first.

**Comment by rmg** [comment]
Actually, the fact that they now fail because this new rule is marked as an error suggests that this PR should bump the major version in `package.json`. If it was only a warning then I would suggest bumping the minor version.

If you bump the major version then the downstream failures _should_ go away because the downstream tests would not pull in the changes from this PR.

This PR is a perfect example of the automated downstream testing identifying a breaking/semver-major change.

**Review by bajtos — APPROVED** [review]
Great addition!

The change must be released as semver-major.

**Comment by superkhau** [comment]
>The change must be released as semver-major.

Agreed.

**Review by rmg — CHANGES_REQUESTED** [review]
The major version should be bumped as part of this PR so that the downstream failures go away.

**Comment by superkhau** [comment]
Above failures are unrelated, should look into it at some point though.

**Pull request merged**
