### PR TITLE
Add CODEOWNER file

### PR DESCRIPTION
**Pull request by dhmlau**
Add CODEOWNER file

### CODE REVIEW

**Review by bajtos — COMMENTED** [review]
IMO, the eslint-config should be owned by more people than just me. I am proposing to add at least @superkhau and @kjdelisle, possibly other people too.

@strongloop/loopback-devs thoughts?

**Comment by kjdelisle** [comment]
@bajtos I worry that if we make the owners @strongloop/loopback-devs , or any sort of mailing list, that it will make people feel more comfortable with the idea that _someone else_ will take care of it, which might very well end up being no one. I think having a few owners explicitly defined would be better.

**Comment by bajtos** [comment]
@kjdelisle Makes sense 👍

**Comment by dhmlau** [comment]
added @kjdelisle  and @superkhau

**Review by bajtos — APPROVED** [review]
:shipit:

**Pull request merged**
