### PR TITLE
Add --ignore-path option to README.md

### PR DESCRIPTION
**Pull request by superkhau**
See https://github.com/eslint/eslint/issues/5848.

@bajtos PTAL

### CODE REVIEW

**Comment by superkhau** [comment]
We should update all projects with the option at some point.

**Comment by bajtos** [comment]
What's the purpose of `--ignore-path`? Why cannot we add the file to `.eslintignore` instead? And why is `eslint` picking `.gitignore` when it's not a javascript file??

**Comment by superkhau** [comment]
From what I understand, it basically tells the linter NOT to lint the files listed in `.gitignore` in addition to the usual ones not linted. The alternative is to list each file individually in `.eslintignore` but that would be duplicating most of the same files in two separate lists. I am proposing to reuse the files listed in `.gitignore` instead since these are the ones we usually want to skip linting for anyways. For example, they do the same in [apiconnect](https://github.ibm.com/apimesh/apiconnect/blob/master/package.json#L9).

**Comment by superkhau** [comment]
See http://eslint.org/docs/user-guide/configuring for more info.

Basically, if you're going to add a file to `.gitignore`, you probably don't want that file linted anyways is what this option is saying. The alternative is to explicitly list each file in `.eslintignore` as you proposed.

I guess the real debate is whether you consider this too "magic" or whether you find it a convience since you don't have to always add the files you `.gitignore` to `.eslintignore`.

**Comment by bajtos** [comment]
http://eslint.org/docs/user-guide/configuring#using-an-alternate-file

> If you’d prefer to use a different file than the .eslintignore in the current working directory, you can specify it on the command line using the --ignore-path option.
> For example, you can use .jshintignore file because it has the same format:
> 
> ```
> eslint --ignore-path .jshintignore file.js
> ```
> 
> You can also use your .gitignore file:
> 
> ```
> eslint --ignore-path .gitignore file.js
> ```
> 
> Any file that follows the standard ignore file format can be used. Keep in mind that specifying --ignore-path means that any existing .eslintignore file will not be used. Note that globbing rules in .eslintignore follow those of .gitignore.

I see, now it makes more sense to me. The catch is that `--ignore-path` tells eslint to use a different file instead of `.eslintignore`. If you need to ignore files that are not in `.gitignore`, then this approach won't work for you.

I am ok with using `--ignore-path .gitignore` as the recommended default approach, as long as our documentation makes it clear when this approach is not suitable (i.e. we need to eslint-ignore additional files) and what to do in such case.

An example of a repository where `--ignore-path .gitignore` won't work is strong-globalize, as it bundles source code of few dependencies inside `deps` folder commited in git. (See https://github.com/strongloop/strong-globalize/pull/70).

**Comment by superkhau** [comment]
I see what you mean with the strong-globalize example. I'm debating whether it's better to account for 99% of the cases where .eslint/.gitignore match versus the 1% of the cases where we keep .eslintignore + .gitignore due to project complexity. I'm leaning towards:

> I am ok with using --ignore-path .gitignore as the recommended default approach, as long as our documentation makes it clear when this approach is not suitable (i.e. we need to eslint-ignore additional files) and what to do in such case

The alternative is just to leave things as they are and add .eslintignore when necessary (which so far I haven't noticed too often either).

Let's close this for now and go with what we do now as this seems like the path to less explaining. If we run into lots of linting issues, let's revisit at that time.

**Pull request closed without merging**
