### PR TITLE
Do not enforce dangling commas

### PR DESCRIPTION
**Pull request by superkhau**
See http://eslint.org/docs/rules/comma-dangle.

### CODE REVIEW

**Comment by superkhau** [comment]
never

**Comment by superkhau** [comment]
always

**Comment by superkhau** [comment]
always-multiline

**Comment by superkhau** [comment]
only-multiline

**Comment by bajtos** [comment]
I have intentionally enabled this rule to improve readability of diffs and make the code archeology easier. It really sucks when you are trying to find who and why changed a particular line of code and in order to find the commit, you have to go through several other commits that were changing the line only to add a trailing comma.

Just to make clear what I mean.

Here is a diff of adding a new item when dangling commas are on:

``` diff
 {
   foo: 'bar',
+  new: true,
 }
```

and here is the diff when dangling commas are disabled:

``` diff
 {
-  foo: 'bar'
+  foo: 'bar',
+  new: true
 }
```

Some people prefer to put commas at line-start to keep diffs small, but that looks even uglier to me:

``` diff
 {
   foo: 'bar'
+, new: true
 }
```

The result:

``` js
{
  foo: 'bar'
, new: true
}
```

**Comment by superkhau** [comment]
@bajtos I actually agree with your for the simplified diffs (I like comma-dangle when it's inside an object or array when listing items to facilitate easier copy/pasting). However, I don't like how the effect spills over to _every_ object and forces us to use `},` on all levels of nested objects. Example:

```
{
  foo: 'bar',
  baz: 'bat', // this
}
[
  foo: 'bar',
  baz: 'bat', // and this is great
]
```

```
hello({
  a: {
    b: {
      c: {
      }, // this
    }, // and
  }, // this is not so hot
});
```

If only there was a way to enforce one without the other. ;(

**Comment by bajtos** [comment]
Looks like the discussion here is rather stalled and I don't see many arguments in favour of disabling comma-dangle, besides up-votes.

Considering that node core uses the same comma-dangle settings too ([proof](https://github.com/nodejs/node/blob/330ea769efe83d4a117c86f482998a9613d51230/.eslintrc#L8)), I am closing this pull request as rejected.

Please do speak up if you strongly disagree and can add new arguments to the discussion.

**Pull request closed without merging**
