### PR TITLE
[SEMVER-MAJOR] Update object-curly-spacing rule

### PR DESCRIPTION
**Pull request by superkhau**
See http://eslint.org/docs/rules/object-curly-spacing

### CODE REVIEW

**Comment by superkhau** [comment]
always

**Comment by superkhau** [comment]
never

**Comment by superkhau** [comment]
always + exception (objecstInObjects and arraysInObjects)

**Comment by superkhau** [comment]
never + exception (objecstInObjects and arraysInObjects)

**Comment by bajtos** [comment]
Let's move this pull request forward. The object-curly-spacing setting is purely stylistic and subjective. Looks that I am the only one that prefers the current style while everybody else prefers `never`. In that case let's go with `never`.

**Pull request merged**
